# Site wide configuration

title: 星海航纪
subtitle: "关于星际移民"
description: "我们去的地方不需要路"
version: "α"
logo: logo-120x120.png # 120x120 px default image used for Twitter summary card
teaser: # 400x250 px default teaser image used in image archive grid
locale: zh-cn
url: http://interimm.org/magazine
baseurl: /magazine

# Jekyll configuration

sass:
    sass_dir: _sass
    style: compressed
permalink: /:categories/:title/
markdown: kramdown
highlighter: pygments
gems:
  - jekyll-sitemap


share: false



# New Settings

cover_image: front-cover.jpg






# Site owner
owner:
  name: "星际移民中心"
  email: interimm@qq.com
  twitter: InterImmCenter
  google:
    ad-client:
    ad-slot: 
  bio: "星际移民中心是一家从事星际移民的机构。"
  avatar: logo-120x120.png # 160x160 px image for author byline
  weibo: 星际移民中心
disqus-shortname: interimmmag
duoshuo-shortname: interimmmag






exclude: ["lib", "config.rb", ".sass-cache", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "*.sublime-project", "*.sublime-workspace", "Gemfile", "Gemfile.lock", "README.md", "LICENSE", "node_modules", "Gruntfile.js", "package.json"]









